# ./docker-compose.yml

version: '3'

services:
  db:
    image: mysql:5.7
    container_name: 'db'
    environment:
      MYSQL_ROOT_PASSWORD: tranducy
      MYSQL_DATABASE: test_db
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    ports:
      - "9906:3306"
    volumes:
      - data:/var/lib/mysql
  web:
    #RUN docker-php-ext-install mysqli && docker-php-ext-enable mysqli && apachectl restart
    image: php:7.2.2-apache
    container_name: php_web
    depends_on:
      - db
    volumes:
      - /Users/mac/Documents/OpenGraph:/var/www/html/
      - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/php.ini
      - ${VHOSTS_DIR-./config/vhosts}:/etc/apache2/sites-enabled
      - ${LOG_DIR-./logs/apache2}:/var/log/apache2
    ports:
      - "8100:80"
    stdin_open: true
    tty: true
    links:
      - db
  phpmyadmin:
    container_name: 'phpmyadmin'
    image: phpmyadmin/phpmyadmin
    links: 
        - db
    ports:
        - 8111:80
    environment:
        MYSQL_USER: devuser
        MYSQL_PASSWORD: devpass
        MYSQL_ROOT_PASSWORD: tranducy
volumes:
  data: